name: androidtv_remote
description: Android TV Remote
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.5

# Add regular dependencies here.
dependencies:
  asn1lib: ^1.4.1
  basic_utils: ^5.6.0
  events_emitter: ^0.5.2
  pointycastle: ^3.7.3
  rsa_encrypt: ^2.0.0
  rsa_pkcs: ^2.0.1
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
